// Locale registry for The Latent Liturgy.
// `voice` = a narrator track in the artist's cloned voice exists (generated by scripts/voiceover.mjs).

export interface LocaleDef {
  code: string
  name: string // native name
  english: string
  rtl?: boolean
  /** Name used when instructing the LLM which language to answer in */
  llm: string
}

export const LOCALES: LocaleDef[] = [
  { code: 'en', name: 'English', english: 'English', llm: 'English' },
  { code: 'pl', name: 'Polski', english: 'Polish', llm: 'Polish' },
  { code: 'de', name: 'Deutsch', english: 'German', llm: 'German' },
  { code: 'fr', name: 'Français', english: 'French', llm: 'French' },
  { code: 'es', name: 'Español', english: 'Spanish', llm: 'Spanish' },
  { code: 'it', name: 'Italiano', english: 'Italian', llm: 'Italian' },
  { code: 'pt', name: 'Português', english: 'Portuguese', llm: 'Portuguese' },
  { code: 'nl', name: 'Nederlands', english: 'Dutch', llm: 'Dutch' },
  { code: 'sv', name: 'Svenska', english: 'Swedish', llm: 'Swedish' },
  { code: 'da', name: 'Dansk', english: 'Danish', llm: 'Danish' },
  { code: 'nb', name: 'Norsk', english: 'Norwegian', llm: 'Norwegian (Bokmål)' },
  { code: 'fi', name: 'Suomi', english: 'Finnish', llm: 'Finnish' },
  { code: 'cs', name: 'Čeština', english: 'Czech', llm: 'Czech' },
  { code: 'sk', name: 'Slovenčina', english: 'Slovak', llm: 'Slovak' },
  { code: 'uk', name: 'Українська', english: 'Ukrainian', llm: 'Ukrainian' },
  { code: 'ru', name: 'Русский', english: 'Russian', llm: 'Russian' },
  { code: 'ro', name: 'Română', english: 'Romanian', llm: 'Romanian' },
  { code: 'hu', name: 'Magyar', english: 'Hungarian', llm: 'Hungarian' },
  { code: 'el', name: 'Ελληνικά', english: 'Greek', llm: 'Greek' },
  { code: 'tr', name: 'Türkçe', english: 'Turkish', llm: 'Turkish' },
  { code: 'ar', name: 'العربية', english: 'Arabic', llm: 'Arabic (Modern Standard)', rtl: true },
  { code: 'he', name: 'עברית', english: 'Hebrew', llm: 'Hebrew', rtl: true },
  { code: 'hi', name: 'हिन्दी', english: 'Hindi', llm: 'Hindi' },
  { code: 'ja', name: '日本語', english: 'Japanese', llm: 'Japanese' },
  { code: 'ko', name: '한국어', english: 'Korean', llm: 'Korean' },
  { code: 'zh', name: '中文', english: 'Chinese', llm: 'Simplified Chinese' },
  { code: 'id', name: 'Bahasa Indonesia', english: 'Indonesian', llm: 'Indonesian' },
  { code: 'vi', name: 'Tiếng Việt', english: 'Vietnamese', llm: 'Vietnamese' },
  { code: 'th', name: 'ไทย', english: 'Thai', llm: 'Thai' },
  { code: 'bg', name: 'Български', english: 'Bulgarian', llm: 'Bulgarian' },
]

export const LOCALE_CODES = LOCALES.map(l => l.code)
export const DEFAULT_LOCALE = 'en'
export const SOURCE_LOCALES = ['en', 'pl'] // hand-written; everything else is machine-translated from `en`

export function getLocale(code: string): LocaleDef {
  return LOCALES.find(l => l.code === code) ?? LOCALES[0]
}

/** Pick the best supported locale for a BCP-47 tag list (navigator.languages). */
export function matchLocale(tags: readonly string[] | undefined): string {
  if (!tags) return DEFAULT_LOCALE
  for (const tag of tags) {
    const lower = tag.toLowerCase()
    const exact = LOCALES.find(l => l.code === lower)
    if (exact) return exact.code
    const base = lower.split('-')[0]
    if (base === 'no' || base === 'nn') return 'nb'
    const partial = LOCALES.find(l => l.code === base)
    if (partial) return partial.code
  }
  return DEFAULT_LOCALE
}

/** Feature packages that ship their own i18n/<lang>.json next to their code. */
export const FEATURE_NAMESPACES = ['curator', 'guide', 'community', 'archaeology'] as const
